service: sentry-lambda-esm-variables
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: server/index.handler
    environment:
      SENTRY_DSN: ${env:SENTRY_DSN}
    events:
      - httpApi:
          path: /
          method: get
